set(sources ${sources}
	src/Utility/CreateForm.h
	src/Utility/CreateForm.cpp
	src/Utility/Function.h
	src/Utility/Function.cpp
	src/Utility/Logger.h
	src/Utility/Logger.cpp
	src/Utility/MessageBox.h
	src/Utility/MessageBox.cpp
	src/Utility/Utility.h
	src/Utility/Utility.cpp
	src/Settings/Config.h
	src/Settings/Config.cpp
	src/Settings/Settings.h
	src/Settings/Settings.cpp
	src/Settings/Conditions.h
	src/Settings/Conditions.cpp
	src/Papyrus/Papyrus.h
	src/Papyrus/Papyrus.cpp
	src/Hooks/Hooks.h
	src/Hooks/Hooks.cpp
	src/DMMF/AlteredCast.h
	src/DMMF/AlteredCast.cpp
	src/DMMF/AlternateAV.h
	src/DMMF/AlternateAV.cpp
	src/DMMF/ChargeTime.h
	src/DMMF/ChargeTime.cpp
	src/DMMF/Cost.h
	src/DMMF/Cost.cpp
	src/DMMF/Magnitude.h
	src/DMMF/Magnitude.cpp
	src/DMMF/Resource.h
	src/DMMF/Resource.cpp
	src/DMMF/Spell.h
	src/DMMF/Spell.cpp
	src/DMMF/DMMF_API.cpp
	src/main.cpp
)
